#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10

BIN="/usr/sbin/nf_conntrack_hello"
NFT_SET="vpn_domains"

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh -c "$BIN $NFT_SET 2>&1 | logger -t nf_conntrack_hello -p daemon.notice"
	procd_close_instance
}
